import type {
  ActivityEvent,
  AgentOverview,
  AnalyticsMetric,
  AnalyticsSnapshotSummary,
  BusinessProfile,
  CalendarEntry,
  ContentItem,
  QueueSummary,
  SettingsCheck,
} from "@/types/content";

export const business: BusinessProfile = {
  id: "biz_nelsonai",
  name: "NelsonAI",
  slug: "nelsonai",
  timezone: "Pacific/Auckland",
  status: "active",
  audience: "Founders, operators, and finance leaders at SMBs adopting AI deliberately.",
  tone: "Direct, practical, credible, and anti-hype.",
  positioning: "AI operating partner for businesses that need usable systems, not vague transformation theater.",
  complianceRules: [
    "Avoid unverifiable performance claims.",
    "Keep advice operational and specific.",
    "Never imply autonomous posting or fully hands-off AI execution.",
  ],
  contentPillars: [
    "AI literacy for leaders",
    "Operational workflow redesign",
    "Risk-aware implementation",
    "Case-study style proof points",
  ],
  enabledPlatforms: ["linkedin", "facebook"],
  postingCadence: {
    linkedin: { posts_per_week: 3 },
    facebook: { posts_per_week: 2 },
  },
  analyticsCadence: "weekly",
  brandProfilePath: "~/.openclaw/workspaces/marketing-ops/businesses/nelsonai/brand-profile.md",
};

export const contentItems: ContentItem[] = [
  {
    id: "item-cfo-literacy",
    businessId: business.id,
    businessSlug: business.slug,
    businessName: business.name,
    title: "Why CFOs need AI literacy in 2026",
    platform: "linkedin",
    scheduledDate: "Mar 17",
    suggestedTime: "9:00 AM",
    campaignTheme: "Leadership readiness",
    topic: "Executive AI literacy",
    state: "ready_to_post",
    priority: "high",
    brief: "Show why finance leaders need enough AI fluency to evaluate operational risk and opportunity without becoming builders.",
    hook: "Your CFO does not need to code. They do need to recognize where AI can quietly create exposure.",
    cta: "Book an intro call",
    currentVersion: {
      id: "ver-1",
      label: "Version 1",
      versionNumber: 1,
      headline: "Why CFOs need AI literacy in 2026",
      body: "Your CFO does not need to code. They do need to recognize where AI can quietly create exposure.\n\nAI literacy for finance leaders is not about prompting tricks. It is about understanding where workflows change, where controls break, and where margin improves.",
      wordCount: 247,
      hook: "Your CFO does not need to code. They do need to recognize where AI can quietly create exposure.",
      cta: "Book an intro call",
      imagePrompt: "Professional CFO portrait with subtle workflow overlays and risk controls motif.",
      imageUrl: "https://placehold.co/1200x675/png?text=CFO+AI+Literacy",
      visualNotes: "Editorial-style portrait with clean dashboard elements, no generic robot imagery.",
      altHooks: [
        "AI risk usually enters through process, not prompts.",
        "Finance leaders do not need deeper tooling. They need sharper pattern recognition.",
      ],
      excerpt: "AI literacy for finance leaders is not about prompting tricks. It is about understanding where workflows change, where controls break, and where margin improves.",
    },
    review: {
      verdict: "PASS",
      confidence: "high",
      reviewer: "Reviewer",
      createdAt: "Thu 12 Mar, 12:10 PM",
    },
    audit: [
      {
        id: "audit-1",
        actor: "orchestrator",
        action: "weekly_plan_ready",
        timestamp: "Thu 12 Mar, 9:20 AM",
        detail: "Planned as part of the leadership readiness batch.",
      },
      {
        id: "audit-2",
        actor: "content-writer",
        action: "draft_created",
        timestamp: "Thu 12 Mar, 10:48 AM",
        detail: "Created version 1 with alternate hooks and visual notes.",
      },
      {
        id: "audit-3",
        actor: "reviewer",
        action: "review_completed",
        timestamp: "Thu 12 Mar, 12:10 PM",
        detail: "PASS with high confidence.",
      },
    ],
    versions: [],
    reviews: [],
  },
  {
    id: "item-hidden-cost",
    businessId: business.id,
    businessSlug: business.slug,
    businessName: business.name,
    title: "The hidden cost of 'we'll do AI later'",
    platform: "linkedin",
    scheduledDate: "Mar 19",
    suggestedTime: "12:00 PM",
    campaignTheme: "Risk and governance",
    topic: "Delay cost",
    state: "ready_to_post",
    priority: "normal",
    brief: "Warn against slow AI adoption by framing the opportunity cost as workflow drag and learning debt.",
    hook: "Every month you wait, your competitors learn one more workflow your team still treats as optional.",
    cta: "DM me",
    currentVersion: {
      id: "ver-2",
      label: "Version 2",
      versionNumber: 2,
      headline: "The hidden cost of 'we'll do AI later'",
      body: "Every month you wait, your competitors learn one more workflow your team still treats as optional.\n\nThe expensive part is not the subscription. It is the compounding drag from decisions your team never redesigned.",
      wordCount: 210,
      hook: "Every month you wait, your competitors learn one more workflow your team still treats as optional.",
      cta: "DM me",
      imagePrompt: "Minimal business illustration showing diverging lines for speed and delay.",
      imageUrl: "https://placehold.co/1200x675/png?text=AI+Delay+Cost",
      visualNotes: "Simple split-path visual with one path accelerating and one stalling.",
      altHooks: ["Delay compounds quietly.", "The cost of waiting is operational, not theoretical."],
      excerpt: "The expensive part is not the subscription. It is the compounding drag from decisions your team never redesigned.",
    },
    review: {
      verdict: "PASS",
      confidence: "high",
      reviewer: "Reviewer",
      createdAt: "Thu 12 Mar, 1:32 PM",
    },
    audit: [
      {
        id: "audit-4",
        actor: "reviewer",
        action: "review_completed",
        timestamp: "Thu 12 Mar, 1:32 PM",
        detail: "PASS and moved to ready-to-post queue.",
      },
    ],
  },
  {
    id: "item-team-ready",
    businessId: business.id,
    businessSlug: business.slug,
    businessName: business.name,
    title: "3 signs your team is ready for AI",
    platform: "facebook",
    scheduledDate: "Mar 18",
    suggestedTime: "6:00 PM",
    campaignTheme: "Readiness signals",
    topic: "Team adoption",
    state: "ready_to_post",
    priority: "high",
    brief: "Make readiness feel tangible with operational signals, not culture slogans.",
    hook: "Most teams think they're not ready. Usually they just haven't looked at the right signals.",
    cta: "Download checklist",
    currentVersion: {
      id: "ver-3",
      label: "Version 2",
      versionNumber: 2,
      headline: "3 signs your team is ready for AI",
      body: "Most teams think they're not ready. Usually they just haven't looked at the right signals.\n\nReadiness shows up in how clearly your team names bottlenecks, documents decisions, and hands work off.",
      wordCount: 211,
      hook: "Most teams think they're not ready. Usually they just haven't looked at the right signals.",
      cta: "Download checklist",
      imagePrompt: "Workshop-style image with a small team around a whiteboard and checklist markers.",
      imageUrl: "https://placehold.co/1200x675/png?text=Team+Ready+For+AI",
      visualNotes: "Warm workshop feel, practical rather than futuristic.",
      altHooks: ["Readiness is visible before tooling changes.", "The best sign is process clarity."],
      excerpt: "Readiness shows up in how clearly your team names bottlenecks, documents decisions, and hands work off.",
    },
    review: {
      verdict: "PASS",
      confidence: "medium",
      reviewer: "Reviewer",
      createdAt: "Thu 12 Mar, 11:32 AM",
      note: "CTA could be stronger if engagement stalls.",
    },
    audit: [
      {
        id: "audit-5",
        actor: "content-writer",
        action: "draft_created",
        timestamp: "Thu 12 Mar, 10:56 AM",
        detail: "Revised examples after initial revise verdict.",
      },
      {
        id: "audit-6",
        actor: "reviewer",
        action: "review_completed",
        timestamp: "Thu 12 Mar, 11:32 AM",
        detail: "PASS with medium confidence.",
      },
    ],
  },
  {
    id: "item-opportunity-snapshot",
    businessId: business.id,
    businessSlug: business.slug,
    businessName: business.name,
    title: "AI opportunity snapshot for operators",
    platform: "linkedin",
    scheduledDate: "Mar 20",
    suggestedTime: "10:30 AM",
    campaignTheme: "Opportunity mapping",
    topic: "Operational bottlenecks",
    state: "briefed",
    priority: "normal",
    brief: "Outline a repeatable framework for spotting small, high-return AI opportunities inside service businesses.",
    hook: "Most AI roadmaps are too big to survive first contact with the business.",
    cta: "Request the worksheet",
    currentVersion: {
      id: "ver-brief",
      label: "Brief only",
      body: "",
      wordCount: 0,
      hook: "Most AI roadmaps are too big to survive first contact with the business.",
      cta: "Request the worksheet",
      excerpt: "Awaiting first draft generation.",
    },
    review: {
      verdict: "REVISE",
      confidence: "low",
      reviewer: "Reviewer",
      createdAt: "Pending",
      note: "Draft not yet available.",
    },
    audit: [
      {
        id: "audit-7",
        actor: "orchestrator",
        action: "brief_created",
        timestamp: "Thu 12 Mar, 8:10 AM",
        detail: "Scheduled for next LinkedIn slot in weekly plan.",
      },
    ],
  },
  {
    id: "item-workflow-friction",
    businessId: business.id,
    businessSlug: business.slug,
    businessName: business.name,
    title: "Stop improvising your social workflow",
    platform: "facebook",
    scheduledDate: "Mar 21",
    suggestedTime: "4:30 PM",
    campaignTheme: "Workflow friction",
    topic: "Publishing chaos",
    state: "revision_required",
    priority: "normal",
    brief: "Explain the hidden cost of improvising every post from scratch.",
    hook: "If every post starts with a blank page, the problem is not creativity. It is your operating system.",
    cta: "See the process map",
    reviewerNote: "Paragraph two includes a claim that needs support.",
    currentVersion: {
      id: "ver-4",
      label: "Version 1",
      versionNumber: 1,
      headline: "Stop improvising your social workflow",
      body: "If every post starts with a blank page, the problem is not creativity. It is your operating system.\n\nA repeatable social workflow protects quality. It gives your team a brief, a review pass, and a clean handoff.",
      wordCount: 238,
      hook: "If every post starts with a blank page, the problem is not creativity. It is your operating system.",
      cta: "See the process map",
      visualNotes: "Simple process board visual.",
      excerpt: "A repeatable social workflow protects quality. It gives your team a brief, a review pass, and a clean handoff.",
    },
    review: {
      verdict: "REVISE",
      confidence: "medium",
      reviewer: "Reviewer",
      createdAt: "Thu 12 Mar, 12:18 PM",
      note: "CTA is vague and one claim needs support.",
    },
    audit: [
      {
        id: "audit-8",
        actor: "reviewer",
        action: "review_completed",
        timestamp: "Thu 12 Mar, 12:18 PM",
        detail: "Requested revision before approval.",
      },
    ],
  },
  {
    id: "item-posted",
    businessId: business.id,
    businessSlug: business.slug,
    businessName: business.name,
    title: "What AI literacy looks like in a leadership team",
    platform: "linkedin",
    scheduledDate: "Mar 10",
    suggestedTime: "9:00 AM",
    campaignTheme: "Leadership readiness",
    topic: "Leadership team capability",
    state: "posted",
    priority: "normal",
    brief: "Show the practical signals of AI literacy in a leadership team.",
    hook: "AI literacy in leadership looks less like experimentation and more like better operational questions.",
    cta: "Book an intro call",
    boostCandidate: true,
    boostReason: "Engagement rate is 2.3x the current LinkedIn average.",
    currentVersion: {
      id: "ver-5",
      label: "Version 1",
      versionNumber: 1,
      headline: "What AI literacy looks like in a leadership team",
      body: "AI literacy in leadership looks less like experimentation and more like better operational questions.",
      wordCount: 176,
      hook: "AI literacy in leadership looks less like experimentation and more like better operational questions.",
      cta: "Book an intro call",
      excerpt: "AI literacy in leadership looks less like experimentation and more like better operational questions.",
    },
    review: {
      verdict: "PASS",
      confidence: "high",
      reviewer: "Reviewer",
      createdAt: "Wed 11 Mar, 4:10 PM",
    },
    audit: [
      {
        id: "audit-9",
        actor: "ben",
        action: "manual_post_marked",
        timestamp: "Wed 11 Mar, 4:40 PM",
        detail: "Marked as scheduled natively on LinkedIn.",
      },
    ],
  },
];

export const activityEvents: ActivityEvent[] = [
  {
    id: "evt-1",
    timestamp: "Thu 12 Mar, 9:00 AM",
    agent: "orchestrator",
    kind: "heartbeat",
    summary: "Weekly planning completed",
    detail: "Created this week's NelsonAI briefs and queued writer work.",
    business: "NelsonAI",
  },
  {
    id: "evt-2",
    timestamp: "Thu 12 Mar, 12:15 PM",
    agent: "reviewer",
    kind: "review",
    summary: "Batch review finished",
    detail: "3 items passed review, 1 item sent back for revision.",
    business: "NelsonAI",
  },
  {
    id: "evt-3",
    timestamp: "Thu 12 Mar, 1:40 PM",
    agent: "telegram-notifier",
    kind: "alert",
    summary: "Batch ready notification sent",
    detail: "Sent one Telegram summary for the three ready-to-post items.",
    business: "NelsonAI",
  },
];

export const analyticsMetrics: AnalyticsMetric[] = [
  { label: "Weekly reach", value: "24.8k", delta: "+18% vs last week" },
  { label: "Average engagement", value: "5.8%", delta: "2 posts above baseline" },
  { label: "Ready-to-post queue", value: "3", delta: "Batch ready" },
  { label: "Review pass rate", value: "75%", delta: "4 reviews this week" },
];

export const analyticsSnapshots: AnalyticsSnapshotSummary[] = [
  {
    id: "snap-1",
    headline: "What AI literacy looks like in a leadership team",
    platform: "linkedin",
    snapshotDate: "2026-03-10",
    engagementRate: 0.078,
    reach: 7900,
    impressions: 8400,
    clicks: 392,
    insights: "Leadership-readiness posts are outperforming broader AI commentary.",
    boostCandidate: true,
  },
  {
    id: "snap-2",
    headline: "3 signs your team is ready for AI",
    platform: "facebook",
    snapshotDate: "2026-03-08",
    engagementRate: 0.052,
    reach: 6100,
    impressions: 6450,
    clicks: 184,
    insights: "Checklist CTA is driving more clicks than narrative CTAs.",
  },
];

export const weeklyCalendar: CalendarEntry[] = [
  {
    day: "Mon",
    date: "Mar 17",
    items: [{ id: "item-cfo-literacy", title: "Why CFOs need AI literacy in 2026", platform: "linkedin", state: "ready_to_post", suggestedTime: "9:00 AM" }],
  },
  {
    day: "Tue",
    date: "Mar 18",
    items: [{ id: "item-team-ready", title: "3 signs your team is ready for AI", platform: "facebook", state: "ready_to_post", suggestedTime: "6:00 PM" }],
  },
  {
    day: "Wed",
    date: "Mar 19",
    items: [{ id: "item-hidden-cost", title: "The hidden cost of 'we'll do AI later'", platform: "linkedin", state: "ready_to_post", suggestedTime: "12:00 PM" }],
  },
  {
    day: "Thu",
    date: "Mar 20",
    items: [{ id: "item-opportunity-snapshot", title: "AI opportunity snapshot for operators", platform: "linkedin", state: "briefed", suggestedTime: "10:30 AM" }],
  },
  {
    day: "Fri",
    date: "Mar 21",
    items: [{ id: "item-workflow-friction", title: "Stop improvising your social workflow", platform: "facebook", state: "revision_required", suggestedTime: "4:30 PM" }],
  },
];

export const settingsChecks: SettingsCheck[] = [
  { label: "Database", value: "Mock mode", tone: "warning" },
  { label: "Telegram notifier", value: "Configured", tone: "success" },
  { label: "LinkedIn analytics", value: "Missing token", tone: "warning" },
  { label: "Facebook analytics", value: "Missing token", tone: "warning" },
  { label: "OpenClaw gateway", value: "Detected via WebSocket client", tone: "success" },
  { label: "Admin auth", value: "Open in dev mode", tone: "neutral" },
];

export const queueSummary: QueueSummary = {
  totalReady: 3,
  linkedInReady: 2,
  facebookReady: 1,
  suggestedRange: "Mar 17 to Mar 19",
};

export const agentOverview: AgentOverview[] = [
  {
    id: "orchestrator",
    name: "Marketing Ops Orchestrator",
    role: "Coordinates planning, drafting, review, and Telegram updates.",
    model: "anthropic/claude-sonnet-4-20250514",
    type: "persistent",
    responsibilities: [
      "Reads content state from Postgres through db-state-manager.",
      "Triggers weekly planning and batch-ready notifications.",
      "Learns from Ben's Telegram feedback via workspace memory and business note files.",
    ],
    workspaceLinks: [
      { label: "SOUL.md", path: "/Users/ben/projects/Dashboard-OpenClaw/openclaw/workspaces/marketing-ops/SOUL.md" },
      { label: "AGENTS.md", path: "/Users/ben/projects/Dashboard-OpenClaw/openclaw/workspaces/marketing-ops/AGENTS.md" },
      { label: "HEARTBEAT.md", path: "/Users/ben/projects/Dashboard-OpenClaw/openclaw/workspaces/marketing-ops/HEARTBEAT.md" },
      { label: "USER.md", path: "/Users/ben/projects/Dashboard-OpenClaw/openclaw/workspaces/marketing-ops/USER.md" },
      { label: "memory.md", path: "/Users/ben/projects/Dashboard-OpenClaw/openclaw/workspaces/marketing-ops/memory/memory.md" },
    ],
  },
  {
    id: "content-writer",
    name: "Content Writer",
    role: "Generates one platform-native draft per task.",
    model: "anthropic/claude-sonnet-4-20250514",
    type: "sub-agent",
    responsibilities: [
      "Writes platform-specific copy from structured briefs.",
      "Returns hooks, body, image prompt, and visual notes.",
      "Applies durable business guidance captured from Ben's Telegram feedback.",
    ],
    workspaceLinks: [
      { label: "content-writer prompt", path: "/Users/ben/projects/Dashboard-OpenClaw/openclaw/workspaces/marketing-ops/prompts/content-writer.md" },
      { label: "linkedin rules", path: "/Users/ben/projects/Dashboard-OpenClaw/openclaw/workspaces/marketing-ops/prompts/platform/linkedin.md" },
      { label: "writer notes", path: "/Users/ben/projects/Dashboard-OpenClaw/openclaw/workspaces/marketing-ops/businesses/nelsonai/writer-notes.md" },
    ],
  },
  {
    id: "reviewer",
    name: "Reviewer",
    role: "Checks brand fit, claim safety, and platform quality.",
    model: "anthropic/claude-sonnet-4-20250514",
    type: "sub-agent",
    responsibilities: [
      "Returns PASS or REVISE with specific notes.",
      "Flags low-confidence outputs for human awareness.",
      "Protects brand fit and factual integrity using durable reviewer guidance.",
    ],
    workspaceLinks: [
      { label: "reviewer prompt", path: "/Users/ben/projects/Dashboard-OpenClaw/openclaw/workspaces/marketing-ops/prompts/reviewer.md" },
      { label: "review checklist", path: "/Users/ben/projects/Dashboard-OpenClaw/openclaw/workspaces/marketing-ops/prompts/shared/review-checklist.md" },
      { label: "reviewer notes", path: "/Users/ben/projects/Dashboard-OpenClaw/openclaw/workspaces/marketing-ops/businesses/nelsonai/reviewer-notes.md" },
    ],
  },
];

export function getItemById(id: string) {
  return contentItems.find((item) => item.id === id);
}
